version: "3.5"

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlserver
    restart: unless-stopped
    environment:
      SA_PASSWORD: "password123Admin789"
      ACCEPT_EULA: "Y"
    ports:
       - "1433:1433"
    networks:
       - testnetwork
  
  redis:
    image: redis
    container_name: redis
    ports:
    - 6379:6379
    networks:
    - testnetwork
    volumes: 
    - redis:/data  

networks:
  testnetwork:
    name: test-network

volumes:
  redis:
    driver: local
